### ISSUE TITLE
скрипт на тестовой странице и в скачиваемом архиве разный

### ISSUE THREAD

**Issue by SkyHolder** [librisius/OliwPageSlider#3]
как минимум нет функции скролла внутри слайда, если слайд больше высоты экрана

**Comment by librisius** [comment]
Данная функция присутствует на третьем слайде. Скролл обычный включается

**Comment by librisius** [comment]
Проверьте и отпишите

**Comment by librisius** [comment]
Скачала, проверила - пример и файлы одинаковы
